name: ci

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Build/Push to GitHub Container Registry
        run:
          make push-multiarch PULL_BASE_REF=$(git describe --tags --abbrev=0) REGISTRY_NAME=ghcr.io/ctrliq BUILD_PLATFORMS="linux amd64 amd64 -amd64; linux arm64 arm64 -arm64"
